# Generated by Django 5.1.7 on 2025-03-29 07:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0002_employee'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Employee',
        ),
    ]
