# Generated by Django 5.1.1 on 2025-05-20 03:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0003_delete_employee'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subtask', models.CharField(max_length=25)),
                ('task_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='todoapp.todos')),
            ],
        ),
    ]
