# Generated by Django 5.1.1 on 2025-05-20 03:48

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0004_subtask'),
    ]

    operations = [
        migrations.AddField(
            model_name='subtask',
            name='created_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
