# Generated by Django 5.1.1 on 2025-05-20 11:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0006_remove_subtask_task_name_subtask_task_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subtask',
            name='task_name',
        ),
        migrations.AddField(
            model_name='subtask',
            name='task_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='todoapp.todos'),
        ),
    ]
