# Generated by Django 5.1.1 on 2025-05-20 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0007_remove_subtask_task_name_subtask_task_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subtask',
            name='task_name',
        ),
        migrations.AddField(
            model_name='subtask',
            name='task_name',
            field=models.ManyToManyField(to='todoapp.todos'),
        ),
    ]
