# Generated by Django 5.1.1 on 2025-05-21 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0009_course_student_studentcourse'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='address',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='mobile_no',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='qualification',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
