# Generated by Django 5.1.1 on 2025-05-21 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0011_alter_student_qualification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='qualification',
            field=models.CharField(blank=True, choices=[('BTech', 'BTech'), ('BBA', 'BBA'), ('BCA', 'BCA'), ('MBA', 'MBA'), ('MTech', 'MTech')], max_length=10, null=True),
        ),
    ]
