# Generated by Django 5.2.1 on 2025-05-31 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0015_alter_student_student_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='student_name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
