# Generated by Django 5.2.1 on 2025-05-31 11:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0020_alter_course_course_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentcourse',
            name='student_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='todoapp.student'),
        ),
        migrations.AlterUniqueTogether(
            name='studentcourse',
            unique_together={('student_name', 'course_name')},
        ),
    ]
