# Generated by Django 5.2.1 on 2025-05-31 11:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0021_alter_studentcourse_student_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentcourse',
            name='student_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='todoapp.student', unique=True),
        ),
    ]
