# Generated by Django 5.2.1 on 2025-06-01 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0024_alter_student_student_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='address',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='qualification',
            field=models.CharField(choices=[('BTech', 'BTech'), ('BBA', 'BBA'), ('BCA', 'BCA'), ('MBA', 'MBA'), ('MTech', 'MTech')], max_length=10),
        ),
    ]
