# Generated by Django 5.2.1 on 2025-06-01 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0025_alter_student_address_alter_student_qualification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='qualification',
            field=models.CharField(choices=[('', 'Select Status'), ('BTech', 'BTech'), ('BBA', 'BBA'), ('BCA', 'BCA'), ('MBA', 'MBA'), ('MTech', 'MTech')], max_length=10),
        ),
    ]
